### ISSUE TITLE
很多时候输入框弹不出来

### ISSUE THREAD

**Issue by zanezha0** [huangruiLearn/HRLChatUi#1]
很多时候输入框弹不出来，点击表情，表情选择也弹不出来，还有文件+号也弹不出来

**Comment by huangruiLearn** [comment]
什么手机？  是不是demo里类没加全   表情那个最开始复制aseets里文件的时候 包名改成你自己应用的包名

**Comment by huangruiLearn** [comment]
> 很多时候输入框弹不出来，点击表情，表情选择也弹不出来，还有文件+号也弹不出来

什么手机？ 是不是demo里类没加全 表情那个最开始复制aseets里文件的时候 包名改成你自己应用的包名

**Comment by zanezha0** [comment]
红米note5   8.1系统   我是直接运行的demo

**Comment by huangruiLearn** [comment]
> 红米note5 8.1系统 我是直接运行的demo

其他手机也不行吗 还是光这个手机不行
