### ISSUE TITLE
db.query()

### ISSUE THREAD

**Issue by AndroidBody** [huangruiLearn/HRLChatUi#11]
Cursor cursor = db.query("emoji", new String[]{"unicodeInt","_id"}, null, null, null, null, null);
没有查询到报错是什么原因

**Comment by huangruiLearn** [comment]
> Cursor cursor = db.query("emoji", new String[]{"unicodeInt","_id"}, null, null, null, null, null);
> 没有查询到报错是什么原因

EmojiDao  CopySqliteFileFromRawToDatabases里包名换成自己的包名了吗
