### ISSUE TITLE
图片高度问题

### ISSUE THREAD

**Issue by wannaliang** [huangruiLearn/HRLChatUi#13]
图片高度不确定，导致图片会被遮挡一部分，导致新发的图片被软键盘遮挡获取再次进入聊天界面无法到达底部

**Comment by nxnyk** [comment]
同问

**Comment by nxnyk** [comment]
复现步骤  点进去 先下拉 获取3条数据 然后发送图片 图片会显示不全

**Comment by nxnyk** [comment]
> 图片高度不确定，导致图片会被遮挡一部分，导致新发的图片被软键盘遮挡获取再次进入聊天界面无法到达底部

老哥你解决了吗？

**Comment by wannaliang** [comment]
试下这个
recyclerView. getViewTreeObserver().addOnGlobalLayoutListener(this);

@Override
public void onGlobalLayout() {

boolean isfullscreen = recyclerView.computeVerticalScrollRange() > recyclerView.computeVerticalScrollExtent();

if (isfullscreen && !linearLayoutManager.getStackFromEnd()){
linearLayoutManager.setStackFromEnd(true);
return;
}

if (!isfullscreen && linearLayoutManager.getStackFromEnd()){
linearLayoutManager.setStackFromEnd(false);
}
}
