### ISSUE TITLE
问个技术问题，请问一下类似微信，点击不同的人进去聊天，总能保持先把消息加载到是怎么处理的

### ISSUE THREAD

**Issue by Alexxiaopang** [huangruiLearn/HRLChatUi#3]
微信每次点击不同的人进去，加载都非常快速把信息处理好展示出来，在好友列表就能接收到信息，请问他们是怎么保存聊天记录的

**Comment by huangruiLearn** [comment]
消息列表保存在本地数据库,一进入聊天界面就从本地数据库取出消息    好友列表收到的消息是以会话的形式存在,也是保存在本地
