### ISSUE TITLE
关于表情框高度问题

### ISSUE THREAD

**Issue by petma** [huangruiLearn/HRLChatUi#5]
模拟器正常，真机，我用的1加6t，9.0的，在聊天界面，直接点表情按钮，弹出的表情面板高度不对，要比软键盘的低一些

**Comment by huangruiLearn** [comment]
> 模拟器正常，真机，我用的1加6t，9.0的，在聊天界面，直接点表情按钮，弹出的表情面板高度不对，要比软键盘的低一些

可能虚拟导航栏引起的吧 我改了下再试试
