### ISSUE TITLE
当虚拟按键隐藏的时候,高度有问题不能正常显示

### ISSUE THREAD

**Issue by Chenshuai770** [huangruiLearn/HRLChatUi#9]
当虚拟按键隐藏的时候,高度有问题不能正常显示

**Comment by huangruiLearn** [comment]
> 当虚拟按键隐藏的时候,高度有问题不能正常显示

修改了 再试试看下

**Comment by Chenshuai770** [comment]
> > 当虚拟按键隐藏的时候,高度有问题不能正常显示
> 
> 修改了 再试试看下

已经可以了
